[jobs.cov]
command = [
    "cargo",
    "tarpaulin",
    "--out",
    "html",
    "--output-dir=./coverage",
    "--exclude-files=cli-man/tests/*",
    "--skip-clean",
]
env.RUST_BACKTRACE = "1"
allow_warnings = true
background = false
need_stdout = true
on_change_strategy = "kill_then_restart"
