[workspace]
resolver = "3"
members = ["cli-man"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Zakaria Mansouri <zakman.dev@gmail.com>"]
license = "MIT"
repository = "https://github.com/zibanpirate/cli-rs"

[workspace.dependencies]
reqwest = "0.12"
zip = "2"
